import { AppShell } from "@/components/app-shell";
import { CaseStatusBadge } from "@/components/case-status";
import { cases, getCaseInvestigation } from "@/lib/api/cases";
import { ArrowLeft, Braces, Check, CheckCircle2, ChevronDown, Database, ExternalLink, FileText, GitBranch, MessageSquareText, ShieldAlert } from "lucide-react";
import Link from "next/link";
import { notFound } from "next/navigation";

export function generateStaticParams() { return cases.map((item) => ({ id:item.id })); }

export default async function CaseDetailPage({ params }: { params:Promise<{id:string}> }) {
  const { id } = await params;
  const item = cases.find((entry) => entry.id === id);
  if (!item) notFound();
  const investigation = getCaseInvestigation(id);
  const completedSteps = investigation.invocations.filter((step) => step.status === "completed" || step.status === "submitted").length;
  const progress = Math.round((completedSteps / investigation.invocations.length) * 100);
  const statusLabel = { completed:"已完成", submitted:"已提交", running:"執行中", pending:"等待中" } as const;
  const stageLabel = (component: string) => component === "Detection" ? "DETECTION" : component.includes("Verdict") ? "VERDICT" : component.includes("Orchestrator") ? "INVESTIGATION" : "AGENT";

  return <AppShell><div className="case-detail">
    <Link href="/cases" className="back-link"><ArrowLeft size={15}/>返回案件列表</Link>
    <div className="case-detail-head"><div><div><code>{item.id}</code><CaseStatusBadge value={item.status}/></div><h1>{item.subject}</h1><p>{item.summary}</p></div><div className="review-actions"><button className="normal-action"><CheckCircle2 size={16}/>標記正常</button><button className="fraud-action"><ShieldAlert size={16}/>確認詐欺</button></div></div>
    <section className="case-summary panel"><div><span>系統判定</span><CaseStatusBadge value={item.verdict}/></div><div><span>Fraud Score</span><strong>{item.fraudScore?.toFixed(2) ?? "尚未產生"}</strong></div><div><span>信心度</span><strong>{item.confidence ? `${Math.round(item.confidence*100)}%` : "—"}</strong></div><div><span>可檢視證據</span><strong>{investigation.evidence.length} 項</strong></div><div><span>Stop Reason</span><strong className="mono-small">{investigation.stopReason}</strong></div></section>

    <section className="panel process-panel"><div className="detail-title"><GitBranch size={18}/><div><h2>判定流程</h2><p>依本次實際執行紀錄動態產生；展開步驟可查看完整輸入、輸出與證據。</p></div><span className="trace-id">{investigation.investigationId}</span></div><div className="flow-progress"><div><span>{item.status === "investigating" ? "調查執行中" : "調查已完成"}</span><b>{completedSteps} / {investigation.invocations.length} 步驟</b></div><i><span style={{width:`${progress}%`}}/></i></div><div className="dynamic-flow">{investigation.invocations.map((invocation) => <details className={`flow-step ${invocation.status}`} key={`${invocation.order}-${invocation.component}`} open={invocation.status === "running"}><summary><span className="flow-marker">{invocation.status === "completed" || invocation.status === "submitted" ? <Check size={13}/> : invocation.status === "running" ? <span className="pulse-dot"/> : invocation.order}</span><div className="flow-identity"><small>{String(invocation.order).padStart(2,"0")} · {stageLabel(invocation.component)}</small>{invocation.agentRef ? <Link href={`/policies/${invocation.agentRef.parent}/${invocation.agentRef.slug}`}>{invocation.component}</Link> : <strong>{invocation.component}</strong>}</div><p>{invocation.reason}</p><span className="flow-evidence">{invocation.evidenceRefs.length || "—"}<small>證據</small></span><span className={`flow-state ${invocation.status}`}>{statusLabel[invocation.status]}</span><ChevronDown className="flow-chevron" size={15}/></summary><div className="flow-detail"><div><label>輸入參照</label><div className="flow-refs">{invocation.inputRefs.length ? invocation.inputRefs.map((ref) => <code key={ref}>{ref}</code>) : <span>無</span>}</div></div><div><label>執行輸出</label><p>{invocation.output}</p></div><div><label>產出／使用證據</label><div className="flow-refs">{invocation.evidenceRefs.length ? invocation.evidenceRefs.map((ref) => <a href={`#${ref}`} key={ref}>{ref}<ExternalLink size={10}/></a>) : <span>尚未產生</span>}</div></div><div className="flow-timing"><label>執行時間</label><strong>{invocation.durationMs} ms</strong></div></div></details>)}</div></section>

    <div className="detail-grid wide-main"><div className="detail-main">
      <section className="panel detail-section"><div className="detail-title"><FileText size={18}/><div><h2>{item.status === "investigating" ? "調查中發現" : "最終判定依據"}</h2><p>{item.status === "investigating" ? "Finding 會隨 Agent 產出逐步更新，完成前不形成最終判定。" : "重要 Finding 必須能追溯到下方的原始證據。"}</p></div></div>{item.status === "investigating" ? <div className="finding-pending"><span className="pulse-dot"/><div><strong>等待 Chat Agent 完成分析</strong><p>目前只有 Detection 初始證據，尚不足以形成 Investigation Fraud Score。</p></div></div> : <><div className="finding fraud-finding"><span>支持詐欺</span><div><strong>外部付款引導行為</strong><p>對話中重複要求買家離開平台付款，使用與既有詐欺案件相同的縮網址域名。</p><a href="#EV-0841-03">EV-0841-03</a><a href="#EV-0841-04">EV-0841-04</a></div><b>高影響</b></div><div className="finding"><span>支持詐欺</span><div><strong>交易與高風險基礎設施重疊</strong><p>平台內無付款紀錄；外部收款帳號與裝置指紋分別關聯多起已確認詐欺案件。</p><a href="#EV-0841-05">EV-0841-05</a><a href="#EV-0841-06">EV-0841-06</a></div><b>高影響</b></div></>}</section>

      <section className="panel detail-section evidence-section"><div className="detail-title"><Database size={18}/><div><h2>Evidence Viewer</h2><p>先看結構化摘要，需要時展開 Raw Data 驗證來源。</p></div><span className="evidence-count">{investigation.evidence.length} EVIDENCE</span></div><div className="evidence-list">{investigation.evidence.map((evidence) => <article className="evidence-card" id={evidence.id} key={evidence.id}><header><div className={`evidence-type ${evidence.type}`}><Database size={15}/></div><div><div><code>{evidence.id}</code><span>{evidence.type.replaceAll("_"," ")}</span></div><strong>{evidence.summary}</strong></div></header><dl><div><dt>來源</dt><dd>{evidence.source}</dd></div><div><dt>蒐集元件</dt><dd>{evidence.collectedBy}</dd></div><div><dt>觀測時間</dt><dd>{evidence.observedAt}</dd></div></dl><details><summary><Braces size={15}/>查看 Raw Data<ChevronDown size={15}/></summary><pre>{JSON.stringify(evidence.raw,null,2)}</pre></details></article>)}</div></section>
    </div><aside className="detail-side">
      <section className="panel detail-section detection-audit"><div className="detail-title"><MessageSquareText size={18}/><div><h2>Detection Result</h2><p>偵測結果不等於系統 Fraud Score。</p></div></div><dl><div><dt>Detected</dt><dd><span className="boolean-true"><Check size={11}/>true</span></dd></div><div><dt>Detector</dt><dd><code>rule_based</code></dd></div><div><dt>Detection ID</dt><dd><code>{investigation.detectionId}</code></dd></div></dl><div className="trigger-list large">{item.triggers.map((trigger) => <span key={trigger}>{trigger}</span>)}</div><details className="raw-detection"><summary><Braces size={14}/>Raw Detector Result<ChevronDown size={14}/></summary><pre>{JSON.stringify({detected:true,subject:{type:item.subjectType,id:item.subject},detector_type:"rule_based",triggers:item.triggers.map((name,index)=>({id:`rule_${index+1}`,name,fired:true})),evidence_refs:["EV-0841-01","EV-0841-02"],raw_result:{matched_rule_count:item.triggers.length,processing_ms:82}},null,2)}</pre></details></section>
      <section className="panel review-note"><span>人工審核</span><h2>請確認系統判定</h2><p>原始資料與處理路徑已完整呈現。操作會保留審核者、時間與備註。</p><label>審核備註（選填）<textarea placeholder="補充判斷依據…"/></label></section>
    </aside></div>
  </div></AppShell>;
}
