"use client";

import { CaseStatusBadge } from "@/components/case-status";
import { systemControlApi } from "@/lib/api/system-control";
import { useQuery } from "@tanstack/react-query";
import { AlertTriangle, ArrowLeft, Braces, Check, ChevronDown, Clock3, Database, FileSearch, GitBranch, RefreshCw } from "lucide-react";
import Link from "next/link";

function object(value: unknown): Record<string, unknown> { return value && typeof value === "object" ? value as Record<string, unknown> : {}; }
function array(value: unknown): unknown[] { return Array.isArray(value) ? value : []; }

export function LiveCaseDetail({ caseId }: { caseId: string }) {
  const query = useQuery({ queryKey:["system-case",caseId],queryFn:()=>systemControlApi.case(caseId),refetchInterval:5000,retry:false });
  if(query.isPending)return <div className="loading" aria-live="polite"><Clock3 className="spin"/>正在讀取案件</div>;
  if(query.isError)return <CaseLoadError message={query.error instanceof Error?query.error.message:"System API unavailable"} retry={()=>query.refetch()}/>;
  const record=query.data;
  if(!record)return <CaseLoadError message={`System Control Plane 找不到 ${caseId}`}/>;
  const result={verdict:record.verdict,confidence:record.confidence,summary:record.summary,stop_reason:record.stop_reason,findings:record.findings,evidence:record.evidence,agents_invoked:record.agents_invoked,scoreboard:record.scoreboard,subject:record.subject};const payload={detection_result:record.detection_result};const detection=record.detection_result;const subject=object(record.subject??detection.subject);const findings=record.findings;const evidence=record.evidence;const agents=record.agents_invoked;const verdict=record.verdict;const running=record.status==="investigating";const status=record.status==="failed"?"review" as const:record.status;const fraudScore=typeof record.scoreboard.fraud_score==="number"?record.scoreboard.fraud_score:null;
  return <div className="case-detail">
    <Link href="/cases" className="back-link"><ArrowLeft size={15}/>返回案件列表</Link>
    <div className="case-detail-head"><div><div><code>{caseId}</code><CaseStatusBadge value={status}/></div><h1>{String(subject.id??"—")}</h1><p>{String(result.summary??record.error??(running?"Investigation 正在執行。":"尚未產生調查結果。"))}</p></div></div>
    <section className="case-summary panel"><div><span>系統判定</span><CaseStatusBadge value={verdict}/></div><div><span>Fraud Score</span><strong>{fraudScore===null?"尚未產生":fraudScore.toFixed(2)}</strong></div><div><span>信心度</span><strong>{typeof result.confidence==="number"?`${Math.round(result.confidence*100)}%`:"—"}</strong></div><div><span>可檢視證據</span><strong>{evidence.length} 項</strong></div><div><span>Stop Reason</span><strong className="mono-small">{String(result.stop_reason??(running?"running":record.error??"—"))}</strong></div></section>
    {record.error&&<section className="panel live-job-error" role="alert"><AlertTriangle/><div><h2>Investigation job 失敗</h2><p>{record.error}</p></div></section>}
    <section className="panel process-panel"><div className="detail-title"><GitBranch size={18}/><div><h2>判定流程</h2><p>依這次 Investigation job 與 agents_invoked 動態產生。</p></div><span className="trace-id">{record.investigation_job_id}</span></div><div className="dynamic-flow"><details className={`flow-step ${running?"running":"completed"}`} open><summary><span className="flow-marker">{running?<span className="pulse-dot"/>:<Check size={13}/>}</span><div className="flow-identity"><small>01 · INVESTIGATION</small><strong>Investigation Orchestrator</strong></div><p>{record.parent_job_id?`Parent ${record.parent_job_id}`:"Manual investigation"}</p><span className="flow-evidence">{evidence.length}<small>證據</small></span><span className={`flow-state ${running?"running":"completed"}`}>{running?"執行中":"已完成"}</span><ChevronDown className="flow-chevron" size={15}/></summary><div className="flow-detail"><div><label>輸入</label><pre>{JSON.stringify(payload,null,2)}</pre></div><div><label>輸出</label><pre>{JSON.stringify(result,null,2)}</pre></div></div></details>{agents.map((agent,index)=><details className="flow-step completed" key={`${String(agent.agent)}:${index}`}><summary><span className="flow-marker"><Check size={13}/></span><div className="flow-identity"><small>{String(index+2).padStart(2,"0")} · AGENT</small><strong>{String(agent.agent??"Agent")}</strong></div><p>{String(agent.reason??"由 Investigation 呼叫")}</p><span className="flow-evidence">—<small>證據</small></span><span className="flow-state completed">已呼叫</span><ChevronDown className="flow-chevron" size={15}/></summary><div className="flow-detail"><pre>{JSON.stringify(agent,null,2)}</pre></div></details>)}</div></section>
    <div className="detail-grid wide-main"><div className="detail-main"><section className="panel detail-section"><div className="detail-title"><FileSearch size={18}/><div><h2>調查發現</h2><p>直接呈現 Investigation result.findings。</p></div></div>{findings.length?findings.map((finding,index)=><div className={`finding ${String(finding.impact)==="supports_fraud"?"fraud-finding":""}`} key={index}><span>{String(finding.impact??"finding")}</span><div><strong>{String(finding.type??"Finding")}</strong><p>{String(finding.description??"")}</p>{array(finding.evidence_refs).map(ref=><a href={`#${String(ref)}`} key={String(ref)}>{String(ref)}</a>)}</div><b>{typeof finding.confidence==="number"?`${Math.round(finding.confidence*100)}%`:"—"}</b></div>):<div className="finding-pending"><div><strong>目前沒有 findings</strong><p>{running?"Job 尚在執行。":"這是後端實際回傳結果。"}</p></div></div>}</section>
    <section className="panel detail-section evidence-section"><div className="detail-title"><Database size={18}/><div><h2>Evidence Viewer</h2><p>展開 Raw Data 驗證實際來源。</p></div><span className="evidence-count">{evidence.length} EVIDENCE</span></div><div className="evidence-list">{evidence.length?evidence.map((item,index)=><article className="evidence-card" id={String(item.id??index)} key={String(item.id??index)}><header><div className="evidence-type"><Database size={15}/></div><div><div><code>{String(item.id??`evidence-${index+1}`)}</code><span>{String(item.type??"evidence")}</span></div><strong>{String(item.summary??item.type??"Evidence record")}</strong></div></header><dl><div><dt>來源</dt><dd>{String(item.source??"—")}</dd></div><div><dt>觀測時間</dt><dd>{String(item.observed_at??"—")}</dd></div></dl><details><summary><Braces size={15}/>查看 Raw Data<ChevronDown size={15}/></summary><pre>{JSON.stringify(item.data??item,null,2)}</pre></details></article>):<div className="empty-table"><Database/><h2>沒有 evidence</h2><p>Investigation 尚未回傳證據。</p></div>}</div></section></div>
    <aside className="detail-side"><section className="panel detail-section detection-audit"><div className="detail-title"><Braces size={18}/><div><h2>Detection Input</h2><p>建立本案件的原始偵測輸入。</p></div></div><pre className="live-json-block">{JSON.stringify(detection,null,2)}</pre></section><section className="panel detail-section"><div className="detail-title"><Clock3 size={18}/><div><h2>Job Metadata</h2></div></div><dl className="live-case-meta"><div><dt>Status</dt><dd>{record.status}</dd></div><div><dt>Investigation Job</dt><dd>{record.investigation_job_id}</dd></div><div><dt>Parent Job</dt><dd>{record.parent_job_id??"—"}</dd></div><div><dt>Updated</dt><dd>{new Date(record.updated_at).toLocaleString("zh-TW",{hour12:false})}</dd></div></dl></section></aside></div>
  </div>;
}

function CaseLoadError({message,retry}:{message:string;retry?:()=>void}){return <div className="error-state" role="alert"><AlertTriangle/><h2>案件無法讀取</h2><p>{message}</p><div>{retry&&<button className="button secondary" onClick={retry}><RefreshCw size={15}/>重新連線</button>} <Link className="button secondary" href="/cases">返回案件列表</Link></div></div>}
