"use client";

import { AlertTriangle, ArrowUpRight, Bot, LoaderCircle, LockKeyhole, Wrench } from "lucide-react";
import Link from "next/link";
import { useQuery } from "@tanstack/react-query";

export type InvestigationAgent = { id:string;name:string;enabled:boolean;prompt:string;prompt_source:string;allowed_tools:string[];primary_subject_types:string[];score_dimensions:string[] };
type Registry={orchestrator:string|null;agents:InvestigationAgent[]};
type Policy={active:{version:string;scoring_policy_version:string;fraud_threshold:number;normal_threshold:number;budget:Record<string,number>;stopping_rules:{rule_id:string;enabled:boolean}[]}|null;versions:unknown[]};

async function get<T>(path:string):Promise<T>{const response=await fetch(`/api/investigation/${path}`);const body=await response.json().catch(()=>({}));if(!response.ok)throw new Error(body.error?.message??body.detail??`Investigation API failed (${response.status})`);return body}

export function InvestigationPolicyLive(){const query=useQuery({queryKey:["investigation","policy-registry"],queryFn:async()=>{const[policy,registry]=await Promise.all([get<Policy>("policies/investigation"),get<Registry>("agents")]);return{policy,registry}},retry:false});if(query.isPending)return <section className="panel model-control-state"><LoaderCircle className="spin"/><div><h2>正在讀取 Investigation runtime</h2></div></section>;if(query.isError)return <section className="panel model-control-state" role="alert"><AlertTriangle/><div><h2>Investigation Policy 無法連線</h2><p>{query.error instanceof Error?query.error.message:"API unavailable"}</p><button onClick={()=>query.refetch()}>重新連線</button></div></section>;const{active}=query.data.policy;const{registry}=query.data;return <><section className="panel subagent-registry"><header><div><Bot size={18}/><div><span>RUNTIME AGENT REGISTRY</span><h2>Investigation 執行成員</h2></div></div><b>{registry.agents.length} 個已註冊</b></header><div className="subagent-grid">{registry.agents.map(agent=><Link href={`/policies/investigation/${agent.id}`} key={agent.id}><div><span className="implementation-state implemented">可用</span><h3>{agent.name}</h3><p>{agent.primary_subject_types.length?`處理 ${agent.primary_subject_types.join("、")}`:"由 Orchestrator 動態派工"}</p></div><ArrowUpRight size={15}/></Link>)}</div></section>{active&&<section className="panel investigation-runtime-policy"><header><div><LockKeyhole size={18}/><div><span>ACTIVE RUNTIME POLICY</span><h2>{active.version}</h2></div></div><code>{active.scoring_policy_version}</code></header><div className="live-policy-meta"><span>Fraud threshold <code>{active.fraud_threshold}</code></span><span>Normal threshold <code>{active.normal_threshold}</code></span><span>Orchestrator <code>{registry.orchestrator??"—"}</code></span></div><div className="investigation-policy-columns"><div><h3>執行預算</h3>{Object.entries(active.budget).map(([key,value])=><p key={key}><span>{key.replaceAll("_"," ")}</span><strong>{value}</strong></p>)}</div><div><h3>停止規則</h3>{active.stopping_rules.map(rule=><p key={rule.rule_id}><span>{rule.rule_id.replaceAll("_"," ")}</span><strong>{rule.enabled?"啟用":"停用"}</strong></p>)}</div></div><footer><LockKeyhole size={14}/><span>目前由 Investigation runtime 載入不可變版本；Dashboard 僅觀測，不直接改寫容器檔案。</span></footer></section>}</>}

export function InvestigationSubAgentLive({id}:{id:string}){const query=useQuery({queryKey:["investigation","agents",id],queryFn:()=>get<Registry>("agents"),retry:false});if(query.isPending)return <section className="panel model-control-state"><LoaderCircle className="spin"/><div><h2>正在讀取 Runtime Registry</h2></div></section>;const agent=query.data?.agents.find(item=>item.id===id);if(query.isError||!agent)return <section className="panel model-control-state" role="alert"><AlertTriangle/><div><h2>找不到 Runtime Agent</h2><p>{query.isError&&query.error instanceof Error?query.error.message:`${id} 不在目前 registry 中`}</p></div></section>;return <div className="agent-detail-grid"><div className="agent-detail-main"><section className="panel prompt-panel"><header><div><Bot size={18}/><div><span>LIVE PROMPT SNAPSHOT</span><h2>{agent.name}</h2></div></div><code>{agent.prompt_source}</code></header><pre>{agent.prompt}</pre><footer><LockKeyhole size={14}/><span>內容直接來自目前 Investigation runtime。</span></footer></section></div><aside className="agent-detail-side"><section className="panel capability-panel"><header><Wrench size={17}/><h2>允許工具</h2></header>{agent.allowed_tools.map(tool=><code key={tool}>{tool}</code>)}</section><section className="panel capability-panel"><header><Bot size={17}/><h2>派工範圍</h2></header>{agent.primary_subject_types.map(type=><p key={type}>{type}</p>)}{agent.score_dimensions.map(item=><code key={item}>{item}</code>)}</section></aside></div>}
