"use client";

import { useDashboardMode } from "@/lib/dashboard-mode";
import { useMutation, useQuery } from "@tanstack/react-query";
import { AlertTriangle, Check, FlaskConical, LoaderCircle, Save, Send, ShieldCheck } from "lucide-react";
import { useEffect, useMemo, useState } from "react";

type Agent="patrol"|"association";type Version={agent:string;strategy:string;version:string;document:Record<string,unknown>;active:boolean;source:string;created_at:string};
const strategies:Record<Agent,string[]>={patrol:["exploit","explore"],association:["focused","discovery"]};
async function request<T>(agent:Agent,path:string,init?:RequestInit):Promise<T>{const response=await fetch(`/api/${agent}/${path}`,{...init,headers:{"content-type":"application/json",...init?.headers}});const body=await response.json().catch(()=>({}));if(!response.ok)throw new Error(body.detail??body.error?.message??`${agent} API failed (${response.status})`);return body}

export function PolicyEditorSwitch({agent,demo}:{agent:Agent;demo:React.ReactNode}){const mode=useDashboardMode();return mode==="demo"?demo:<LiveAgentPolicyEditor agent={agent}/>}

function LiveAgentPolicyEditor({agent}:{agent:Agent}){const[selection,setSelection]=useState(strategies[agent][0]);const[text,setText]=useState("");const[notice,setNotice]=useState("");const query=useQuery({queryKey:[agent,"policies"],queryFn:()=>request<Version[]>(agent,`policies/${agent}`),retry:false});const active=useMemo(()=>query.data?.find(item=>item.strategy===selection&&item.active)??query.data?.find(item=>item.strategy===selection),[query.data,selection]);useEffect(()=>{if(active)setText(JSON.stringify(active.document,null,2))},[active]);const action=useMutation({mutationFn:async(kind:"validate"|"drafts"|"publish")=>{const document=JSON.parse(text) as Record<string,unknown>;return request<Record<string,unknown>>(agent,`policies/${agent}/${selection}/${kind}`,{method:"POST",body:JSON.stringify(document)})},onSuccess:(_,kind)=>{setNotice(kind==="validate"?"驗證通過":kind==="drafts"?"草稿已寫入資料庫":"已發布並切換 Active Policy");query.refetch()},onError:error=>setNotice(error instanceof Error?error.message:"操作失敗")});if(query.isPending)return <section className="panel model-control-state"><LoaderCircle className="spin"/><div><h2>正在讀取 {agent} policies</h2></div></section>;if(query.isError)return <section className="panel model-control-state" role="alert"><AlertTriangle/><div><h2>{agent} Policy 無法連線</h2><p>{query.error instanceof Error?query.error.message:"API unavailable"}</p><button onClick={()=>query.refetch()}>重新連線</button></div></section>;return <section className="panel live-policy-editor"><header><div><ShieldCheck size={18}/><div><span>LIVE VERSIONED POLICY</span><h2>Policy 控制</h2></div></div><strong>{active?.version??"尚未發布"}</strong></header><div className="policy-strategy-tabs" role="tablist" aria-label="Policy strategy">{strategies[agent].map(strategy=><button type="button" role="tab" aria-selected={selection===strategy} className={selection===strategy?"active":""} key={strategy} onClick={()=>{setSelection(strategy);setNotice("")}}>{strategy}</button>)}</div><div className="live-policy-meta"><span>Active version <code>{active?.version??"—"}</code></span><span>Source <code>{active?.source??"—"}</code></span><span>{query.data?.filter(item=>item.strategy===selection).length??0} versions</span></div><label className="policy-json-editor"><span>Policy document</span><textarea value={text} onChange={event=>setText(event.target.value)} spellCheck={false} aria-label={`${agent} ${selection} policy JSON`}/></label><footer><div aria-live="polite">{notice&&<><Check size={14}/><span>{notice}</span></>}</div><div><button disabled={action.isPending} onClick={()=>action.mutate("validate")}><FlaskConical size={15}/>Validate</button><button disabled={action.isPending} onClick={()=>action.mutate("drafts")}><Save size={15}/>Save draft</button><button className="primary" disabled={action.isPending} onClick={()=>action.mutate("publish")}><Send size={15}/>Publish</button></div></footer></section>}
